/*
 Waves v0.6.4
 http://fian.my.id/Waves

 Copyright 2014 Alfiana E. Sibuea and other contributors
 Released under the MIT license
 https://github.com/fians/Waves/blob/master/LICENSE
 VelocityJS.org (1.2.2). (C) 2014 Julian Shapiro. MIT @license: en.wikipedia.org/wiki/MIT_License  VelocityJS.org jQuery Shim (1.0.1). (C) 2014 The jQuery Foundation. MIT @license: en.wikipedia.org/wiki/MIT_License. */
(function(e){function t(c){var g="",d;for(d in c)c.hasOwnProperty(d)&&(g+=d+":"+c[d]+";");return g}function b(g){if(!1===c.allowEvent(g))var b=null;else{b=null;for(var d=g.target||g.srcElement;null!==d.parentElement;){if(!(d instanceof SVGElement)&&-1!==d.className.indexOf("waves-effect")){b=d;break}else if(d.classList.contains("waves-effect")){b=d;break}d=d.parentElement}}null!==b&&(m.show(g,b),"ontouchstart"in e&&(b.addEventListener("touchend",m.hide,!1),b.addEventListener("touchcancel",m.hide,
!1)),b.addEventListener("mouseup",m.hide,!1),b.addEventListener("mouseleave",m.hide,!1))}var g=g||{},y=document.querySelectorAll.bind(document),m={duration:750,show:function(c,g){if(2===c.button)return!1;var d=g||this,b=document.createElement("div");b.className="waves-ripple";d.appendChild(b);var N={top:0,left:0};var l=d&&d.ownerDocument;var e=l.documentElement;"undefined"!==typeof d.getBoundingClientRect&&(N=d.getBoundingClientRect());var n=null!==l&&l===l.window?l:9===l.nodeType&&l.defaultView;
l=N.top+n.pageYOffset-e.clientTop;e=N.left+n.pageXOffset-e.clientLeft;N=c.pageY-l;n=c.pageX-e;d="scale("+d.clientWidth/100*10+")";"touches"in c&&(N=c.touches[0].pageY-l,n=c.touches[0].pageX-e);b.setAttribute("data-hold",Date.now());b.setAttribute("data-scale",d);b.setAttribute("data-x",n);b.setAttribute("data-y",N);l={top:N+"px",left:n+"px"};b.className+=" waves-notransition";b.setAttribute("style",t(l));b.className=b.className.replace("waves-notransition","");l["-webkit-transform"]=d;l["-moz-transform"]=
d;l["-ms-transform"]=d;l["-o-transform"]=d;l.transform=d;l.opacity="1";l["-webkit-transition-duration"]=m.duration+"ms";l["-moz-transition-duration"]=m.duration+"ms";l["-o-transition-duration"]=m.duration+"ms";l["transition-duration"]=m.duration+"ms";l["-webkit-transition-timing-function"]="cubic-bezier(0.250, 0.460, 0.450, 0.940)";l["-moz-transition-timing-function"]="cubic-bezier(0.250, 0.460, 0.450, 0.940)";l["-o-transition-timing-function"]="cubic-bezier(0.250, 0.460, 0.450, 0.940)";l["transition-timing-function"]=
"cubic-bezier(0.250, 0.460, 0.450, 0.940)";b.setAttribute("style",t(l))},hide:function(b){c.touchup(b);var g=this,d=null;b=g.getElementsByClassName("waves-ripple");if(0<b.length)d=b[b.length-1];else return!1;var e=d.getAttribute("data-x"),N=d.getAttribute("data-y"),l=d.getAttribute("data-scale");b=350-(Date.now()-Number(d.getAttribute("data-hold")));0>b&&(b=0);setTimeout(function(){d.setAttribute("style",t({top:N+"px",left:e+"px",opacity:"0","-webkit-transition-duration":m.duration+"ms","-moz-transition-duration":m.duration+
"ms","-o-transition-duration":m.duration+"ms","transition-duration":m.duration+"ms","-webkit-transform":l,"-moz-transform":l,"-ms-transform":l,"-o-transform":l,transform:l}));setTimeout(function(){try{g.removeChild(d)}catch(R){return!1}},m.duration)},b)},wrapInput:function(c){for(var b=0;b<c.length;b++){var d=c[b];if("input"===d.tagName.toLowerCase()){var g=d.parentNode;if("i"!==g.tagName.toLowerCase()||-1===g.className.indexOf("waves-effect")){var e=document.createElement("i");e.className=d.className+
" waves-input-wrapper";var l=d.getAttribute("style");l||(l="");e.setAttribute("style",l);d.className="waves-button-input";d.removeAttribute("style");g.replaceChild(e,d);e.appendChild(d)}}}}},c={touches:0,allowEvent:function(b){var g=!0;"touchstart"===b.type?c.touches+=1:"touchend"===b.type||"touchcancel"===b.type?setTimeout(function(){0<c.touches&&--c.touches},500):"mousedown"===b.type&&0<c.touches&&(g=!1);return g},touchup:function(b){c.allowEvent(b)}};g.displayEffect=function(c){c=c||{};"duration"in
c&&(m.duration=c.duration);m.wrapInput(y(".waves-effect"));"ontouchstart"in e&&document.body.addEventListener("touchstart",b,!1);document.body.addEventListener("mousedown",b,!1)};g.attach=function(c){"input"===c.tagName.toLowerCase()&&(m.wrapInput([c]),c=c.parentElement);"ontouchstart"in e&&c.addEventListener("touchstart",b,!1);c.addEventListener("mousedown",b,!1)};e.Waves=g;document.addEventListener("DOMContentLoaded",function(){g.displayEffect()},!1)})(window);
!function(e){function t(d){var c=d.length,g=b.type(d);return"function"===g||b.isWindow(d)?!1:1===d.nodeType&&c?!0:"array"===g||0===c||"number"==typeof c&&0<c&&c-1 in d}if(!e.jQuery){var b=function(d,c){return new b.fn.init(d,c)};b.isWindow=function(d){return null!=d&&d==d.window};b.type=function(d){return null==d?d+"":"object"==typeof d||"function"==typeof d?y[c.call(d)]||"object":typeof d};b.isArray=Array.isArray||function(d){return"array"===b.type(d)};b.isPlainObject=function(d){var c;if(!d||"object"!==
b.type(d)||d.nodeType||b.isWindow(d))return!1;try{if(d.constructor&&!m.call(d,"constructor")&&!m.call(d.constructor.prototype,"isPrototypeOf"))return!1}catch(N){return!1}for(c in d);return void 0===c||m.call(d,c)};b.each=function(d,c,b){var g,e=0,n=d.length,q=t(d);if(b)if(q)for(;n>e&&(g=c.apply(d[e],b),!1!==g);e++);else for(e in d){if(g=c.apply(d[e],b),!1===g)break}else if(q)for(;n>e&&(g=c.call(d[e],e,d[e]),!1!==g);e++);else for(e in d)if(g=c.call(d[e],e,d[e]),!1===g)break;return d};b.data=function(d,
c,e){if(void 0===e){e=(d=d[b.expando])&&g[d];if(void 0===c)return e;if(e&&c in e)return e[c]}else if(void 0!==c)return d=d[b.expando]||(d[b.expando]=++b.uuid),g[d]=g[d]||{},g[d][c]=e,e};b.removeData=function(c,e){var d=c[b.expando],l=d&&g[d];l&&b.each(e,function(c,d){delete l[d]})};b.extend=function(){var c,g,e,l,m=arguments[0]||{},n=1,q=arguments.length,t=!1;"boolean"==typeof m&&(t=m,m=arguments[n]||{},n++);"object"!=typeof m&&"function"!==b.type(m)&&(m={});for(n===q&&(m=this,n--);q>n;n++)if(null!=
(e=arguments[n]))for(g in e){var y=m[g];var k=e[g];m!==k&&(t&&k&&(b.isPlainObject(k)||(c=b.isArray(k)))?(c?(c=!1,l=y&&b.isArray(y)?y:[]):l=y&&b.isPlainObject(y)?y:{},m[g]=b.extend(t,l,k)):void 0!==k&&(m[g]=k))}return m};b.queue=function(c,g,e){function d(c,d){var g=d||[];if(null!=c)if(t(Object(c))){var b="string"==typeof c?[c]:c;for(var k=+b.length,e=0,h=g.length;k>e;)g[h++]=b[e++];if(k!==k)for(;void 0!==b[e];)g[h++]=b[e++];b=(g.length=h,g);!b}else[].push.call(g,c);return g}if(c){g=(g||"fx")+"queue";
var m=b.data(c,g);return e?(!m||b.isArray(e)?m=b.data(c,g,d(e)):m.push(e),m):m||[]}};b.dequeue=function(c,g){b.each(c.nodeType?[c]:c,function(c,d){g=g||"fx";var e=b.queue(d,g),l=e.shift();"inprogress"===l&&(l=e.shift());l&&("fx"===g&&e.unshift("inprogress"),l.call(d,function(){b.dequeue(d,g)}))})};b.fn=b.prototype={init:function(c){if(c.nodeType)return this[0]=c,this;throw Error("Not a DOM node.");},offset:function(){var c=this[0].getBoundingClientRect?this[0].getBoundingClientRect():{top:0,left:0};
return{top:c.top+(e.pageYOffset||document.scrollTop||0)-(document.clientTop||0),left:c.left+(e.pageXOffset||document.scrollLeft||0)-(document.clientLeft||0)}},position:function(){function c(){return this.offsetParent||document||document}var g=this[0];c=c.apply(g);var e=this.offset(),l=/^(?:body|html)$/i.test(c.nodeName)?{top:0,left:0}:b(c).offset();return e.top-=parseFloat(g.style.marginTop)||0,e.left-=parseFloat(g.style.marginLeft)||0,c.style&&(l.top+=parseFloat(c.style.borderTopWidth)||0,l.left+=
parseFloat(c.style.borderLeftWidth)||0),{top:e.top-l.top,left:e.left-l.left}}};var g={};b.expando="velocity"+(new Date).getTime();b.uuid=0;for(var y={},m=y.hasOwnProperty,c=y.toString,E="Boolean Number String Function Array Date RegExp Object Error".split(" "),x=0;x<E.length;x++)y["[object "+E[x]+"]"]=E[x].toLowerCase();b.fn.init.prototype=b.fn;e.Velocity={Utilities:b}}}(window);
(function(e){"object"==typeof module&&"object"==typeof module.exports?module.exports=e():"function"==typeof define&&define.amd?define(e):e()})(function(){return function(e,t,b,g){function y(a){for(var c=-1,f=a?a.length:0,g=[];++c<f;){var d=a[c];d&&g.push(d)}return g}function m(a){return n.isWrapped(a)?a=[].slice.call(a):n.isNode(a)&&(a=[a]),a}function c(a){a=q.data(a,"velocity");return null===a?g:a}function E(a){return function(c){return 1/a*Math.round(c*a)}}function x(a,c,f,g){function B(a,f,c){return(((1-
3*c+3*f)*a+(3*c-6*f))*a+3*f)*a}var d="Float32Array"in t;if(4!==arguments.length)return!1;for(var b=0;4>b;++b)if("number"!=typeof arguments[b]||isNaN(arguments[b])||!isFinite(arguments[b]))return!1;a=Math.min(a,1);f=Math.min(f,1);a=Math.max(a,0);f=Math.max(f,0);var h=d?new Float32Array(11):Array(11),e=!1;d=function(d){if(!e&&(e=!0,a!=c||f!=g))for(var b=0;11>b;++b)h[b]=B(.1*b,a,f);if(a!==c||f!==g)if(0===d)d=0;else if(1===d)d=1;else{var k=0;for(b=1;10!=b&&h[b]<=d;++b)k+=.1;--b;b=k+(d-h[b])/(h[b+1]-h[b])*
.1;var L=3*(1-3*f+3*a)*b*b+2*(3*f-6*a)*b+3*a;if(.001<=L){for(k=0;4>k;++k){L=3*(1-3*f+3*a)*b*b+2*(3*f-6*a)*b+3*a;if(0===L)break;var T=B(b,a,f)-d;b-=T/L}d=b}else if(0==L)d=b;else{b=k;k+=.1;var r=0;do T=b+(k-b)/2,L=B(T,a,f)-d,0<L?k=T:b=T;while(1E-7<Math.abs(L)&&10>++r);d=T}d=B(d,c,g)}return d};d.getControlPoints=function(){return[{x:a,y:c},{x:f,y:g}]};var k="generateBezier("+[a,c,f,g]+")";return d.toString=function(){return k},d}function d(a,c){var f=a;return n.isString(a)?k.Easings[a]||(f=!1):f=n.isArray(a)&&
1===a.length?E.apply(null,a):n.isArray(a)&&2===a.length?ea.apply(null,a.concat([c])):n.isArray(a)&&4===a.length?x.apply(null,a):!1,!1===f&&(f=k.Easings[k.defaults.easing]?k.defaults.easing:aa),f}function Z(a){if(a){a=(new Date).getTime();var b=k.State.calls.length;1E4<b&&(k.State.calls=y(k.State.calls));for(var f=0;b>f;f++)if(k.State.calls[f]){var d=k.State.calls[f],e=d[0],r=d[2],u=d[3],l=!!u,m=null;u||(u=k.State.calls[f][3]=a-16);for(var V=Math.min((a-u)/r.duration,1),t=0,I=e.length;I>t;t++){var Q=
e[t],M=Q.element;if(c(M)){var v=!1;r.display!==g&&null!==r.display&&"none"!==r.display&&("flex"===r.display&&q.each(["-webkit-box","-moz-box","-ms-flexbox","-webkit-flex"],function(a,f){h.setPropertyValue(M,"display",f)}),h.setPropertyValue(M,"display",r.display));r.visibility!==g&&"hidden"!==r.visibility&&h.setPropertyValue(M,"visibility",r.visibility);for(var x in Q)if("element"!==x){var w=Q[x],z=n.isString(w.easing)?k.Easings[w.easing]:w.easing;if(1===V)var E=w.endValue;else{var H=w.endValue-w.startValue;
if(E=w.startValue+H*z(V,r,H),!l&&E===w.currentValue)continue}if(w.currentValue=E,"tween"===x)m=E;else{if(h.Hooks.registered[x]){var J=h.Hooks.getRoot(x);(z=c(M).rootPropertyValueCache[J])&&(w.rootPropertyValue=z)}w=h.setPropertyValue(M,x,w.currentValue+(0===parseFloat(E)?"":w.unitType),w.rootPropertyValue,w.scrollData);h.Hooks.registered[x]&&(c(M).rootPropertyValueCache[J]=h.Normalizations.registered[J]?h.Normalizations.registered[J]("extract",null,w[1]):w[1]);"transform"===w[0]&&(v=!0)}}r.mobileHA&&
c(M).transformCache.translate3d===g&&(c(M).transformCache.translate3d="(0px, 0px, 0px)",v=!0);v&&h.flushTransformCache(M)}}r.display!==g&&"none"!==r.display&&(k.State.calls[f][2].display=!1);r.visibility!==g&&"hidden"!==r.visibility&&(k.State.calls[f][2].visibility=!1);r.progress&&r.progress.call(d[1],d[1],V,Math.max(0,u+r.duration-a),u,m);1===V&&N(f)}}k.State.isTicking&&fa(Z)}function N(a,b){if(!k.State.calls[a])return!1;for(var f=k.State.calls[a][0],d=k.State.calls[a][1],B=k.State.calls[a][2],e=
k.State.calls[a][4],u=!1,l=0,m=f.length;m>l;l++){var n=f[l].element;if(b||B.loop||("none"===B.display&&h.setPropertyValue(n,"display",B.display),"hidden"===B.visibility&&h.setPropertyValue(n,"visibility",B.visibility)),!0!==B.loop&&(q.queue(n)[1]===g||!/\.velocityQueueEntryFlag/i.test(q.queue(n)[1]))&&c(n)){c(n).isAnimating=!1;c(n).rootPropertyValueCache={};var t=!1;q.each(h.Lists.transforms3D,function(a,f){var b=/^scale/.test(f)?1:0,d=c(n).transformCache[f];c(n).transformCache[f]!==g&&(new RegExp("^\\("+
b+"[^.]")).test(d)&&(t=!0,delete c(n).transformCache[f])});B.mobileHA&&(t=!0,delete c(n).transformCache.translate3d);t&&h.flushTransformCache(n);h.Values.removeClass(n,"velocity-animating")}if(!b&&B.complete&&!B.loop&&l===m-1)try{B.complete.call(d,d)}catch(I){setTimeout(function(){throw I;},1)}e&&!0!==B.loop&&e(d);c(n)&&!0===B.loop&&!b&&(q.each(c(n).tweensContainer,function(a,f){/^rotate/.test(a)&&360===parseFloat(f.endValue)&&(f.endValue=0,f.startValue=360);/^backgroundPosition/.test(a)&&100===parseFloat(f.endValue)&&
"%"===f.unitType&&(f.endValue=0,f.startValue=100)}),k(n,"reverse",{loop:!0,delay:B.delay}));!1!==B.queue&&q.dequeue(n,B.queue)}k.State.calls[a]=!1;f=0;for(d=k.State.calls.length;d>f;f++)if(!1!==k.State.calls[f]){u=!0;break}!1===u&&(k.State.isTicking=!1,delete k.State.calls,k.State.calls=[])}var l=function(){if(b.documentMode)return b.documentMode;for(var a=7;4<a;a--){var c=b.createElement("div");if(c.innerHTML="\x3c!--[if IE "+a+"]><span></span><![endif]--\x3e",c.getElementsByTagName("span").length)return a}return g}(),
R=function(){var a=0;return t.webkitRequestAnimationFrame||t.mozRequestAnimationFrame||function(c){var f=(new Date).getTime(),b;return b=Math.max(0,16-(f-a)),a=f+b,setTimeout(function(){c(f+b)},b)}}(),n={isString:function(a){return"string"==typeof a},isArray:Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},isFunction:function(a){return"[object Function]"===Object.prototype.toString.call(a)},isNode:function(a){return a&&a.nodeType},isNodeList:function(a){return"object"==
typeof a&&/^\[object (HTMLCollection|NodeList|Object)\]$/.test(Object.prototype.toString.call(a))&&a.length!==g&&(0===a.length||"object"==typeof a[0]&&0<a[0].nodeType)},isWrapped:function(a){return a&&(a.jquery||t.Zepto&&t.Zepto.zepto.isZ(a))},isSVG:function(a){return t.SVGElement&&a instanceof t.SVGElement},isEmptyObject:function(a){for(var c in a)return!1;return!0}},q,S=!1;if(e.fn&&e.fn.jquery?(q=e,S=!0):q=t.Velocity.Utilities,8>=l&&!S)throw Error("Velocity: IE8 and below require jQuery to be loaded before Velocity.");
if(7>=l)return void(jQuery.fn.velocity=jQuery.fn.animate);var aa="swing",k={State:{isMobile:/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isAndroid:/Android/i.test(navigator.userAgent),isGingerbread:/Android 2\.3\.[3-7]/i.test(navigator.userAgent),isChrome:t.chrome,isFirefox:/Firefox/i.test(navigator.userAgent),prefixElement:b.createElement("div"),prefixMatches:{},scrollAnchor:null,scrollPropertyLeft:null,scrollPropertyTop:null,isTicking:!1,calls:[]},CSS:{},
Utilities:q,Redirects:{},Easings:{},Promise:t.Promise,defaults:{queue:"",duration:400,easing:aa,begin:g,complete:g,progress:g,display:g,visibility:g,loop:!1,delay:!1,mobileHA:!0,_cacheValues:!0},init:function(a){q.data(a,"velocity",{isSVG:n.isSVG(a),isAnimating:!1,computedStyle:null,tweensContainer:null,rootPropertyValueCache:{},transformCache:{}})},hook:null,mock:!1,version:{major:1,minor:2,patch:2},debug:!1};t.pageYOffset!==g?(k.State.scrollAnchor=t,k.State.scrollPropertyLeft="pageXOffset",k.State.scrollPropertyTop=
"pageYOffset"):(k.State.scrollAnchor=b.documentElement||b.body.parentNode||b.body,k.State.scrollPropertyLeft="scrollLeft",k.State.scrollPropertyTop="scrollTop");var ea=function(){function a(a,c,b){var f=a.v+b.dv*c;return{dx:f,dv:-a.tension*(a.x+b.dx*c)-a.friction*f}}function c(f,c){var b={dx:f.v,dv:-f.tension*f.x-f.friction*f.v},d=a(f,.5*c,b),g=a(f,.5*c,d),B=a(f,c,g),h=1/6*(b.dv+2*(d.dv+g.dv)+B.dv);return f.x+=1/6*(b.dx+2*(d.dx+g.dx)+B.dx)*c,f.v+=h*c,f}return function u(a,b,d){var g={x:-1,v:0,tension:null,
friction:null},B=[0],h=0,e,k,l;a=parseFloat(a)||500;b=parseFloat(b)||20;d=d||null;g.tension=a;g.friction=b;for((e=null!==d)?(h=u(a,b),k=h/d*.016):k=.016;l=c(l||g,k),B.push(1+l.x),h+=16,1E-4<Math.abs(l.x)&&1E-4<Math.abs(l.v););return e?function(a){return B[a*(B.length-1)|0]}:h}}();k.Easings={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},spring:function(a){return 1-Math.cos(4.5*a*Math.PI)*Math.exp(6*-a)}};q.each([["ease",[.25,.1,.25,1]],["ease-in",[.42,0,1,1]],["ease-out",
[0,0,.58,1]],["ease-in-out",[.42,0,.58,1]],["easeInSine",[.47,0,.745,.715]],["easeOutSine",[.39,.575,.565,1]],["easeInOutSine",[.445,.05,.55,.95]],["easeInQuad",[.55,.085,.68,.53]],["easeOutQuad",[.25,.46,.45,.94]],["easeInOutQuad",[.455,.03,.515,.955]],["easeInCubic",[.55,.055,.675,.19]],["easeOutCubic",[.215,.61,.355,1]],["easeInOutCubic",[.645,.045,.355,1]],["easeInQuart",[.895,.03,.685,.22]],["easeOutQuart",[.165,.84,.44,1]],["easeInOutQuart",[.77,0,.175,1]],["easeInQuint",[.755,.05,.855,.06]],
["easeOutQuint",[.23,1,.32,1]],["easeInOutQuint",[.86,0,.07,1]],["easeInExpo",[.95,.05,.795,.035]],["easeOutExpo",[.19,1,.22,1]],["easeInOutExpo",[1,0,0,1]],["easeInCirc",[.6,.04,.98,.335]],["easeOutCirc",[.075,.82,.165,1]],["easeInOutCirc",[.785,.135,.15,.86]]],function(a,c){k.Easings[c[0]]=x.apply(null,c[1])});var h=k.CSS={RegEx:{isHex:/^#([A-f\d]{3}){1,2}$/i,valueUnwrap:/^[A-z]+\((.*)\)$/i,wrappedValueAlreadyExtracted:/[0-9.]+ [0-9.]+ [0-9.]+( [0-9.]+)?/,valueSplit:/([A-z]+\(.+\))|(([A-z0-9#-.]+?)(?=\s|$))/gi},
Lists:{colors:"fill stroke stopColor color backgroundColor borderColor borderTopColor borderRightColor borderBottomColor borderLeftColor outlineColor".split(" "),transformsBase:"translateX translateY scale scaleX scaleY skewX skewY rotateZ".split(" "),transforms3D:["transformPerspective","translateZ","scaleZ","rotateX","rotateY"]},Hooks:{templates:{textShadow:["Color X Y Blur","black 0px 0px 0px"],boxShadow:["Color X Y Blur Spread","black 0px 0px 0px 0px"],clip:["Top Right Bottom Left","0px 0px 0px 0px"],
backgroundPosition:["X Y","0% 0%"],transformOrigin:["X Y Z","50% 50% 0px"],perspectiveOrigin:["X Y","50% 50%"]},registered:{},register:function(){for(var a=0;a<h.Lists.colors.length;a++)h.Hooks.templates[h.Lists.colors[a]]=["Red Green Blue Alpha","color"===h.Lists.colors[a]?"0 0 0 1":"255 255 255 1"];var c;if(l)for(c in h.Hooks.templates){var f=h.Hooks.templates[c];var b=f[0].split(" ");f=f[1].match(h.RegEx.valueSplit);"Color"===b[0]&&(b.push(b.shift()),f.push(f.shift()),h.Hooks.templates[c]=[b.join(" "),
f.join(" ")])}for(c in h.Hooks.templates)for(a in f=h.Hooks.templates[c],b=f[0].split(" "),b)h.Hooks.registered[c+b[a]]=[c,a]},getRoot:function(a){var c=h.Hooks.registered[a];return c?c[0]:a},cleanRootPropertyValue:function(a,c){return h.RegEx.valueUnwrap.test(c)&&(c=c.match(h.RegEx.valueUnwrap)[1]),h.Values.isCSSNullValue(c)&&(c=h.Hooks.templates[a][1]),c},extractValue:function(a,c){var f=h.Hooks.registered[a];if(f){var b=f[1];return c=h.Hooks.cleanRootPropertyValue(f[0],c),c.toString().match(h.RegEx.valueSplit)[b]}return c},
injectValue:function(a,c,f){if(a=h.Hooks.registered[a]){var b=a[1],d;return f=h.Hooks.cleanRootPropertyValue(a[0],f),d=f.toString().match(h.RegEx.valueSplit),d[b]=c,d.join(" ")}return f}},Normalizations:{registered:{clip:function(a,c,f){switch(a){case "name":return"clip";case "extract":var b;return h.RegEx.wrappedValueAlreadyExtracted.test(f)?b=f:(b=f.toString().match(h.RegEx.valueUnwrap),b=b?b[1].replace(/,(\s+)?/g," "):f),b;case "inject":return"rect("+f+")"}},blur:function(a,c,f){switch(a){case "name":return k.State.isFirefox?
"filter":"-webkit-filter";case "extract":return a=parseFloat(f),a||0===a||(a=(f=f.toString().match(/blur\(([0-9]+[A-z]+)\)/i))?f[1]:0),a;case "inject":return parseFloat(f)?"blur("+f+")":"none"}},opacity:function(a,c,f){if(8>=l)switch(a){case "name":return"filter";case "extract":return(a=f.toString().match(/alpha\(opacity=(.*)\)/i))?a[1]/100:1;case "inject":return c.style.zoom=1,1<=parseFloat(f)?"":"alpha(opacity="+parseInt(100*parseFloat(f),10)+")"}else switch(a){case "name":return"opacity";case "extract":return f;
case "inject":return f}}},register:function(){9>=l||k.State.isGingerbread||(h.Lists.transformsBase=h.Lists.transformsBase.concat(h.Lists.transforms3D));for(var a=0;a<h.Lists.transformsBase.length;a++)!function(){var b=h.Lists.transformsBase[a];h.Normalizations.registered[b]=function(a,d,h){switch(a){case "name":return"transform";case "extract":return c(d)===g||c(d).transformCache[b]===g?/^scale/i.test(b)?1:0:c(d).transformCache[b].replace(/[()]/g,"");case "inject":a=!1;switch(b.substr(0,b.length-
1)){case "translate":a=!/(%|px|em|rem|vw|vh|\d)$/i.test(h);break;case "scal":case "scale":k.State.isAndroid&&c(d).transformCache[b]===g&&1>h&&(h=1);a=!/(\d)$/i.test(h);break;case "skew":a=!/(deg|\d)$/i.test(h);break;case "rotate":a=!/(deg|\d)$/i.test(h)}return a||(c(d).transformCache[b]="("+h+")"),c(d).transformCache[b]}}}();for(a=0;a<h.Lists.colors.length;a++)!function(){var c=h.Lists.colors[a];h.Normalizations.registered[c]=function(a,b,d){switch(a){case "name":return c;case "extract":if(!h.RegEx.wrappedValueAlreadyExtracted.test(d)){var f;
a={black:"rgb(0, 0, 0)",blue:"rgb(0, 0, 255)",gray:"rgb(128, 128, 128)",green:"rgb(0, 128, 0)",red:"rgb(255, 0, 0)",white:"rgb(255, 255, 255)"};/^[A-z]+$/i.test(d)?f=a[d]!==g?a[d]:a.black:h.RegEx.isHex.test(d)?f="rgb("+h.Values.hexToRgb(d).join(" ")+")":/^rgba?\(/i.test(d)||(f=a.black);d=(f||d).toString().match(h.RegEx.valueUnwrap)[1].replace(/,(\s+)?/g," ")}return 8>=l||3!==d.split(" ").length||(d+=" 1"),d;case "inject":return 8>=l?4===d.split(" ").length&&(d=d.split(/\s+/).slice(0,3).join(" ")):
3===d.split(" ").length&&(d+=" 1"),(8>=l?"rgb":"rgba")+"("+d.replace(/\s+/g,",").replace(/\.(\d)+(?=,)/g,"")+")"}}}()}},Names:{camelCase:function(a){return a.replace(/-(\w)/g,function(a,c){return c.toUpperCase()})},SVGAttribute:function(a){var c="width|height|x|y|cx|cy|r|rx|ry|x1|x2|y1|y2";return(l||k.State.isAndroid&&!k.State.isChrome)&&(c+="|transform"),(new RegExp("^("+c+")$","i")).test(a)},prefixCheck:function(a){if(k.State.prefixMatches[a])return[k.State.prefixMatches[a],!0];for(var c=["","Webkit",
"Moz","ms","O"],b=0,d=c.length;d>b;b++){var g;if(g=0===b?a:c[b]+a.replace(/^\w/,function(a){return a.toUpperCase()}),n.isString(k.State.prefixElement.style[g]))return k.State.prefixMatches[a]=g,[g,!0]}return[a,!1]}},Values:{hexToRgb:function(a){var c;return a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,c,b,d){return c+c+b+b+d+d}),c=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a),c?[parseInt(c[1],16),parseInt(c[2],16),parseInt(c[3],16)]:[0,0,0]},isCSSNullValue:function(a){return 0==
a||/^(none|auto|transparent|(rgba\(0, ?0, ?0, ?0\)))$/i.test(a)},getUnitType:function(a){return/^(rotate|skew)/i.test(a)?"deg":/(^(scale|scaleX|scaleY|scaleZ|alpha|flexGrow|flexHeight|zIndex|fontWeight)$)|((opacity|red|green|blue|alpha)$)/i.test(a)?"":"px"},getDisplayType:function(a){a=a&&a.tagName.toString().toLowerCase();return/^(b|big|i|small|tt|abbr|acronym|cite|code|dfn|em|kbd|strong|samp|var|a|bdo|br|img|map|object|q|script|span|sub|sup|button|input|label|select|textarea)$/i.test(a)?"inline":
/^(li)$/i.test(a)?"list-item":/^(tr)$/i.test(a)?"table-row":/^(table)$/i.test(a)?"table":/^(tbody)$/i.test(a)?"table-row-group":"block"},addClass:function(a,c){a.classList?a.classList.add(c):a.className+=(a.className.length?" ":"")+c},removeClass:function(a,c){a.classList?a.classList.remove(c):a.className=a.className.toString().replace(new RegExp("(^|\\s)"+c.split(" ").join("|")+"(\\s|$)","gi")," ")}},getPropertyValue:function(a,b,d,e){function f(a,b){function d(){m&&h.setPropertyValue(a,"display",
"none")}var k=0;if(8>=l)k=q.css(a,b);else{var m=!1;if(/^(width|height)$/.test(b)&&0===h.getPropertyValue(a,"display")&&(m=!0,h.setPropertyValue(a,"display",h.Values.getDisplayType(a))),!e){if("height"===b&&"border-box"!==h.getPropertyValue(a,"boxSizing").toString().toLowerCase())return k=a.offsetHeight-(parseFloat(h.getPropertyValue(a,"borderTopWidth"))||0)-(parseFloat(h.getPropertyValue(a,"borderBottomWidth"))||0)-(parseFloat(h.getPropertyValue(a,"paddingTop"))||0)-(parseFloat(h.getPropertyValue(a,
"paddingBottom"))||0),d(),k;if("width"===b&&"border-box"!==h.getPropertyValue(a,"boxSizing").toString().toLowerCase())return k=a.offsetWidth-(parseFloat(h.getPropertyValue(a,"borderLeftWidth"))||0)-(parseFloat(h.getPropertyValue(a,"borderRightWidth"))||0)-(parseFloat(h.getPropertyValue(a,"paddingLeft"))||0)-(parseFloat(h.getPropertyValue(a,"paddingRight"))||0),d(),k}k=c(a)===g?t.getComputedStyle(a,null):c(a).computedStyle?c(a).computedStyle:c(a).computedStyle=t.getComputedStyle(a,null);"borderColor"===
b&&(b="borderTopColor");k=9===l&&"filter"===b?k.getPropertyValue(b):k[b];""!==k&&null!==k||(k=a.style[b]);d()}if("auto"===k&&/^(top|right|bottom|left)$/i.test(b)){var u=f(a,"position");("fixed"===u||"absolute"===u&&/top|left/i.test(b))&&(k=q(a).position()[b]+"px")}return k}if(h.Hooks.registered[b]){var m=h.Hooks.getRoot(b);d===g&&(d=h.getPropertyValue(a,h.Names.prefixCheck(m)[0]));h.Normalizations.registered[m]&&(d=h.Normalizations.registered[m]("extract",a,d));var u=h.Hooks.extractValue(b,d)}else h.Normalizations.registered[b]&&
(d=h.Normalizations.registered[b]("name",a),"transform"!==d&&(m=f(a,h.Names.prefixCheck(d)[0]),h.Values.isCSSNullValue(m)&&h.Hooks.templates[b]&&(m=h.Hooks.templates[b][1])),u=h.Normalizations.registered[b]("extract",a,m));if(!/^[\d-]/.test(u))if(c(a)&&c(a).isSVG&&h.Names.SVGAttribute(b))if(/^(height|width)$/i.test(b))try{u=a.getBBox()[b]}catch(G){u=0}else u=a.getAttribute(b);else u=f(a,h.Names.prefixCheck(b)[0]);return h.Values.isCSSNullValue(u)&&(u=0),2<=k.debug&&console.log("Get "+b+": "+u),u},
setPropertyValue:function(a,b,d,g,e){var f=b;if("scroll"===b)e.container?e.container["scroll"+e.direction]=d:"Left"===e.direction?t.scrollTo(d,e.alternateValue):t.scrollTo(e.alternateValue,d);else if(h.Normalizations.registered[b]&&"transform"===h.Normalizations.registered[b]("name",a))h.Normalizations.registered[b]("inject",a,d),f="transform",d=c(a).transformCache[b];else{h.Hooks.registered[b]&&(e=b,b=h.Hooks.getRoot(b),g=g||h.getPropertyValue(a,b),d=h.Hooks.injectValue(e,d,g));if(h.Normalizations.registered[b]&&
(d=h.Normalizations.registered[b]("inject",a,d),b=h.Normalizations.registered[b]("name",a)),f=h.Names.prefixCheck(b)[0],8>=l)try{a.style[f]=d}catch(u){k.debug&&console.log("Browser does not support ["+d+"] for ["+f+"]")}else c(a)&&c(a).isSVG&&h.Names.SVGAttribute(b)?a.setAttribute(b,d):a.style[f]=d;2<=k.debug&&console.log("Set "+b+" ("+f+"): "+d)}return[f,d]},flushTransformCache:function(a){function b(b){return parseFloat(h.getPropertyValue(a,b))}var d="";if((l||k.State.isAndroid&&!k.State.isChrome)&&
c(a).isSVG){var g={translate:[b("translateX"),b("translateY")],skewX:[b("skewX")],skewY:[b("skewY")],scale:1!==b("scale")?[b("scale"),b("scale")]:[b("scaleX"),b("scaleY")],rotate:[b("rotateZ"),0,0]};q.each(c(a).transformCache,function(a){/^translate/i.test(a)?a="translate":/^scale/i.test(a)?a="scale":/^rotate/i.test(a)&&(a="rotate");g[a]&&(d+=a+"("+g[a].join(" ")+") ",delete g[a])})}else{var e,m;q.each(c(a).transformCache,function(b){return e=c(a).transformCache[b],"transformPerspective"===b?(m=e,
!0):(9===l&&"rotateZ"===b&&(b="rotate"),void(d+=b+e+" "))});m&&(d="perspective"+m+" "+d)}h.setPropertyValue(a,"transform",d)}};h.Hooks.register();h.Normalizations.register();k.hook=function(a,b,d){var f=g;return a=m(a),q.each(a,function(a,h){if(c(h)===g&&k.init(h),d===g)f===g&&(f=k.CSS.getPropertyValue(h,b));else{var e=k.CSS.setPropertyValue(h,b,d);"transform"===e[0]&&k.CSS.flushTransformCache(h);f=e}}),f};var H=function(){function a(){return l?I.promise||null:y}function e(){function a(a){function v(a,
b){var c=g,k=g,l=g;return n.isArray(a)?(c=a[0],!n.isArray(a[1])&&/^[\d-]/.test(a[1])||n.isFunction(a[1])||h.RegEx.isHex.test(a[1])?l=a[1]:(n.isString(a[1])&&!h.RegEx.isHex.test(a[1])||n.isArray(a[1]))&&(k=b?a[1]:d(a[1],e.duration),a[2]!==g&&(l=a[2]))):c=a,b||(k=k||e.easing),n.isFunction(c)&&(c=c.call(f,E,x)),n.isFunction(l)&&(l=l.call(f,E,x)),[c||0,k,l]}function B(a,b){var c,d;return d=(b||"0").toString().toLowerCase().replace(/[%A-z]+$/,function(a){return c=a,""}),c||(c=h.Values.getUnitType(a)),
[d,c]}function y(){var a=f.parentNode||b.body,d=h.getPropertyValue(f,"position"),e=h.getPropertyValue(f,"fontSize"),g=d===z.lastPosition&&a===z.lastParent,l=e===z.lastFontSize;z.lastParent=a;z.lastPosition=d;z.lastFontSize=e;var m={};if(l&&g)m.emToPx=z.lastEmToPx,m.percentToPxWidth=z.lastPercentToPxWidth,m.percentToPxHeight=z.lastPercentToPxHeight;else{var n=c(f).isSVG?b.createElementNS("http://www.w3.org/2000/svg","rect"):b.createElement("div");k.init(n);a.appendChild(n);q.each(["overflow","overflowX",
"overflowY"],function(a,b){k.CSS.setPropertyValue(n,b,"hidden")});k.CSS.setPropertyValue(n,"position",d);k.CSS.setPropertyValue(n,"fontSize",e);k.CSS.setPropertyValue(n,"boxSizing","content-box");q.each("minWidth maxWidth width minHeight maxHeight height".split(" "),function(a,b){k.CSS.setPropertyValue(n,b,"100%")});k.CSS.setPropertyValue(n,"paddingLeft","100em");m.percentToPxWidth=z.lastPercentToPxWidth=(parseFloat(h.getPropertyValue(n,"width",null,!0))||1)/100;m.percentToPxHeight=z.lastPercentToPxHeight=
(parseFloat(h.getPropertyValue(n,"height",null,!0))||1)/100;m.emToPx=z.lastEmToPx=(parseFloat(h.getPropertyValue(n,"paddingLeft"))||1)/100;a.removeChild(n)}return null===z.remToPx&&(z.remToPx=parseFloat(h.getPropertyValue(b.body,"fontSize"))||16),null===z.vwToPx&&(z.vwToPx=parseFloat(t.innerWidth)/100,z.vhToPx=parseFloat(t.innerHeight)/100),m.remToPx=z.remToPx,m.vwToPx=z.vwToPx,m.vhToPx=z.vhToPx,1<=k.debug&&console.log("Unit ratios: "+JSON.stringify(m),f),m}if(e.begin&&0===E)try{e.begin.call(u,u)}catch(xa){setTimeout(function(){throw xa;
},1)}if("scroll"===Q){var r=/^x$/i.test(e.axis)?"Left":"Top",D=parseFloat(e.offset)||0,C,W,A;e.container?n.isWrapped(e.container)||n.isNode(e.container)?(e.container=e.container[0]||e.container,C=e.container["scroll"+r],A=C+q(f).position()[r.toLowerCase()]+D):e.container=null:(C=k.State.scrollAnchor[k.State["scrollProperty"+r]],W=k.State.scrollAnchor[k.State["scrollProperty"+("Left"===r?"Top":"Left")]],A=q(f).offset()[r.toLowerCase()]+D);l={scroll:{rootPropertyValue:!1,startValue:C,currentValue:C,
endValue:A,unitType:"",easing:e.easing,scrollData:{container:e.container,direction:r,alternateValue:W}},element:f};k.debug&&console.log("tweensContainer (scroll): ",l.scroll,f)}else if("reverse"===Q){if(!c(f).tweensContainer)return void q.dequeue(f,e.queue);"none"===c(f).opts.display&&(c(f).opts.display="auto");"hidden"===c(f).opts.visibility&&(c(f).opts.visibility="visible");c(f).opts.loop=!1;c(f).opts.begin=null;c(f).opts.complete=null;F.easing||delete e.easing;F.duration||delete e.duration;e=q.extend({},
c(f).opts,e);r=q.extend(!0,{},c(f).tweensContainer);for(var w in r)"element"!==w&&(D=r[w].startValue,r[w].startValue=r[w].currentValue=r[w].endValue,r[w].endValue=D,n.isEmptyObject(F)||(r[w].easing=e.easing),k.debug&&console.log("reverse tweensContainer ("+w+"): "+JSON.stringify(r[w]),f));l=r}else if("start"===Q){c(f).tweensContainer&&!0===c(f).isAnimating&&(r=c(f).tweensContainer);q.each(G,function(a,b){if(RegExp("^"+h.Lists.colors.join("$|^")+"$").test(a)){var c=v(b,!0),d=c[0],e=c[1],f=c[2];if(h.RegEx.isHex.test(d)){c=
["Red","Green","Blue"];d=h.Values.hexToRgb(d);f=f?h.Values.hexToRgb(f):g;for(var k=0;k<c.length;k++){var l=[d[k]];e&&l.push(e);f!==g&&l.push(f[k]);G[a+c[k]]=l}delete G[a]}}});for(D in G)if(A=v(G[D]),C=A[0],W=A[1],A=A[2],D=h.Names.camelCase(D),a=h.Hooks.getRoot(D),w=!1,c(f).isSVG||"tween"===a||!1!==h.Names.prefixCheck(a)[1]||h.Normalizations.registered[a]!==g){(e.display!==g&&null!==e.display&&"none"!==e.display||e.visibility!==g&&"hidden"!==e.visibility)&&/opacity|filter/.test(D)&&!A&&0!==C&&(A=0);
e._cacheValues&&r&&r[D]?(A===g&&(A=r[D].endValue+r[D].unitType),w=c(f).rootPropertyValueCache[a]):h.Hooks.registered[D]?A===g?(w=h.getPropertyValue(f,a),A=h.getPropertyValue(f,D,w)):w=h.Hooks.templates[a][1]:A===g&&(A=h.getPropertyValue(f,D));var L,J,H=!1;if(L=B(D,A),A=L[0],a=L[1],L=B(D,C),C=L[0].replace(/^([+-\/*])=/,function(a,b){return H=b,""}),J=L[1],A=parseFloat(A)||0,C=parseFloat(C)||0,"%"===J&&(/^(fontSize|lineHeight)$/.test(D)?(C/=100,J="em"):/^scale/.test(D)?(C/=100,J=""):/(Red|Green|Blue)$/i.test(D)&&
(C=C/100*255,J="")),/[\/*]/.test(H))J=a;else if(a!==J&&0!==A)if(0===C)J=a;else{m=m||y();var M=/margin|padding|left|right|width|text|word|letter/i.test(D)||/X$/.test(D)||"x"===D?"x":"y";switch(a){case "%":A*="x"===M?m.percentToPxWidth:m.percentToPxHeight;break;case "px":break;default:A*=m[a+"ToPx"]}switch(J){case "%":A*=1/("x"===M?m.percentToPxWidth:m.percentToPxHeight);break;case "px":break;default:A*=1/m[J+"ToPx"]}}switch(H){case "+":C=A+C;break;case "-":C=A-C;break;case "*":C*=A;break;case "/":C=
A/C}l[D]={rootPropertyValue:w,startValue:A,currentValue:A,endValue:C,unitType:J,easing:W};k.debug&&console.log("tweensContainer ("+D+"): "+JSON.stringify(l[D]),f)}else k.debug&&console.log("Skipping ["+a+"] due to a lack of browser support.");l.element=f}l.element&&(h.Values.addClass(f,"velocity-animating"),R.push(l),""===e.queue&&(c(f).tweensContainer=l,c(f).opts=e),c(f).isAnimating=!0,E===x-1?(k.State.calls.push([R,u,e,null,I.resolver]),!1===k.State.isTicking&&(k.State.isTicking=!0,Z())):E++)}var f=
this,e=q.extend({},k.defaults,F),l={},m;switch(c(f)===g&&k.init(f),parseFloat(e.delay)&&!1!==e.queue&&q.queue(f,e.queue,function(a){k.velocityQueueEntryFlag=!0;c(f).delayTimer={setTimeout:setTimeout(a,parseFloat(e.delay)),next:a}}),e.duration.toString().toLowerCase()){case "fast":e.duration=200;break;case "normal":e.duration=400;break;case "slow":e.duration=600;break;default:e.duration=parseFloat(e.duration)||1}!1!==k.mock&&(!0===k.mock?e.duration=e.delay=1:(e.duration*=parseFloat(k.mock)||1,e.delay*=
parseFloat(k.mock)||1));e.easing=d(e.easing,e.duration);e.begin&&!n.isFunction(e.begin)&&(e.begin=null);e.progress&&!n.isFunction(e.progress)&&(e.progress=null);e.complete&&!n.isFunction(e.complete)&&(e.complete=null);e.display!==g&&null!==e.display&&(e.display=e.display.toString().toLowerCase(),"auto"===e.display&&(e.display=k.CSS.Values.getDisplayType(f)));e.visibility!==g&&null!==e.visibility&&(e.visibility=e.visibility.toString().toLowerCase());e.mobileHA=e.mobileHA&&k.State.isMobile&&!k.State.isGingerbread;
!1===e.queue?e.delay?setTimeout(a,e.delay):a():q.queue(f,e.queue,function(b,c){return!0===c?(I.promise&&I.resolver(u),!0):(k.velocityQueueEntryFlag=!0,void a(b))});""!==e.queue&&"fx"!==e.queue||"inprogress"===q.queue(f)[0]||q.dequeue(f)}var f=arguments[0]&&(arguments[0].p||q.isPlainObject(arguments[0].properties)&&!arguments[0].properties.names||n.isString(arguments[0].properties)),l,y,r,u,G,F;if(n.isWrapped(this)?(l=!1,r=0,u=this,y=this):(l=!0,r=1,u=f?arguments[0].elements||arguments[0].e:arguments[0]),
u=m(u)){f?(G=arguments[0].properties||arguments[0].p,F=arguments[0].options||arguments[0].o):(G=arguments[r],F=arguments[r+1]);var x=u.length,E=0;if(!/^(stop|finish)$/i.test(G)&&!q.isPlainObject(F))for(F={},f=r+1;f<arguments.length;f++)n.isArray(arguments[f])||!/^(fast|normal|slow)$/i.test(arguments[f])&&!/^\d/.test(arguments[f])?n.isString(arguments[f])||n.isArray(arguments[f])?F.easing=arguments[f]:n.isFunction(arguments[f])&&(F.complete=arguments[f]):F.duration=arguments[f];var I={promise:null,
resolver:null,rejecter:null};l&&k.Promise&&(I.promise=new k.Promise(function(a,b){I.resolver=a;I.rejecter=b}));switch(G){case "scroll":var Q="scroll";break;case "reverse":Q="reverse";break;case "finish":case "stop":q.each(u,function(a,b){c(b)&&c(b).delayTimer&&(clearTimeout(c(b).delayTimer.setTimeout),c(b).delayTimer.next&&c(b).delayTimer.next(),delete c(b).delayTimer)});var M=[];return q.each(k.State.calls,function(a,b){b&&q.each(b[1],function(d,e){var f=F===g?"":F;return!0===f||b[2].queue===f||
F===g&&!1===b[2].queue?void q.each(u,function(d,g){g===e&&((!0===F||n.isString(F))&&(q.each(q.queue(g,n.isString(F)?F:""),function(a,b){n.isFunction(b)&&b(null,!0)}),q.queue(g,n.isString(F)?F:"",[])),"stop"===G?(c(g)&&c(g).tweensContainer&&!1!==f&&q.each(c(g).tweensContainer,function(a,b){b.endValue=b.currentValue}),M.push(a)):"finish"===G&&(b[2].duration=1))}):!0})}),"stop"===G&&(q.each(M,function(a,b){N(b,!0)}),I.promise&&I.resolver(u)),a();default:if(!q.isPlainObject(G)||n.isEmptyObject(G)){if(n.isString(G)&&
k.Redirects[G]){var v=q.extend({},F),S=v.duration,w=v.delay||0;return!0===v.backwards&&(u=q.extend(!0,[],u).reverse()),q.each(u,function(a,b){parseFloat(v.stagger)?v.delay=w+parseFloat(v.stagger)*a:n.isFunction(v.stagger)&&(v.delay=w+v.stagger.call(b,a,x));v.drag&&(v.duration=parseFloat(S)||(/^(callout|transition)/.test(G)?1E3:400),v.duration=Math.max(v.duration*(v.backwards?1-a/x:(a+1)/x),.75*v.duration,200));k.Redirects[G].call(b,b,v||{},a,x,u,I.promise?I:g)}),a()}f="Velocity: First argument ("+
G+") was not a property map, a known action, or a registered redirect. Aborting.";return I.promise?I.rejecter(Error(f)):console.log(f),a()}Q="start"}var z={lastParent:null,lastPosition:null,lastFontSize:null,lastPercentToPxWidth:null,lastPercentToPxHeight:null,lastEmToPx:null,remToPx:null,vwToPx:null,vhToPx:null},R=[];q.each(u,function(a,b){n.isNode(b)&&e.call(b)});v=q.extend({},k.defaults,F);if(v.loop=parseInt(v.loop),f=2*v.loop-1,v.loop)for(r=0;f>r;r++){var X={delay:v.delay,progress:v.progress};
r===f-1&&(X.display=v.display,X.visibility=v.visibility,X.complete=v.complete);H(u,"reverse",X)}return a()}};k=q.extend(H,k);k.animate=H;var fa=t.requestAnimationFrame||R;return k.State.isMobile||b.hidden===g||b.addEventListener("visibilitychange",function(){b.hidden?(fa=function(a){return setTimeout(function(){a(!0)},16)},Z()):fa=t.requestAnimationFrame||R}),e.Velocity=k,e!==t&&(e.fn.velocity=H,e.fn.velocity.defaults=k.defaults),q.each(["Down","Up"],function(a,b){k.Redirects["slide"+b]=function(a,
c,d,e,h,l){c=q.extend({},c);var f=c.begin,m=c.complete,n={height:"",marginTop:"",marginBottom:"",paddingTop:"",paddingBottom:""},r={};c.display===g&&(c.display="Down"===b?"inline"===k.CSS.Values.getDisplayType(a)?"inline-block":"block":"none");c.begin=function(){f&&f.call(h,h);for(var c in n){r[c]=a.style[c];var d=k.CSS.getPropertyValue(a,c);n[c]="Down"===b?[d,0]:[0,d]}r.overflow=a.style.overflow;a.style.overflow="hidden"};c.complete=function(){for(var b in r)a.style[b]=r[b];m&&m.call(h,h);l&&l.resolver(h)};
k(a,n,c)}}),q.each(["In","Out"],function(a,b){k.Redirects["fade"+b]=function(a,c,d,e,h,l){a=q.extend({},c);c={opacity:"In"===b?1:0};var f=a.complete;a.complete=d!==e-1?a.begin=null:function(){f&&f.call(h,h);l&&l.resolver(h)};a.display===g&&(a.display="In"===b?"auto":"none");k(this,c,a)}}),k}(window.jQuery||window.Zepto||window,window,document)});
!function(e,t,b,g){function y(a,b,c){return setTimeout(Z(a,c),b)}function m(a,b,d){return Array.isArray(a)?(c(a,d[b],d),!0):!1}function c(a,b,c){var p;if(a)if(a.forEach)a.forEach(b,c);else if(a.length!==g)for(p=0;p<a.length;)b.call(c,a[p],p,a),p++;else for(p in a)a.hasOwnProperty(p)&&b.call(c,a[p],p,a)}function E(a,b,c){for(var p=Object.keys(b),d=0;d<p.length;)(!c||c&&a[p[d]]===g)&&(a[p[d]]=b[p[d]]),d++;return a}function x(a,b){return E(a,b,!0)}function d(a,b,c){var p=b.prototype;b=a.prototype=Object.create(p);
b.constructor=a;b._super=p;c&&E(b,c)}function Z(a,b){return function(){return a.apply(b,arguments)}}function N(a,b){return typeof a==D?a.apply(b?b[0]||g:g,b):a}function l(a,b,d){c(q(b),function(b){a.addEventListener(b,d,!1)})}function R(a,b,d){c(q(b),function(b){a.removeEventListener(b,d,!1)})}function n(a,b){for(;a;){if(a==b)return!0;a=a.parentNode}return!1}function q(a){return a.trim().split(/\s+/g)}function S(a,b,c){if(a.indexOf&&!c)return a.indexOf(b);for(var p=0;p<a.length;){if(c&&a[p][c]==b||
!c&&a[p]===b)return p;p++}return-1}function aa(a){return Array.prototype.slice.call(a,0)}function k(a,b,c){for(var p=[],d=[],e=0;e<a.length;){var f=b?a[e][b]:a[e];0>S(d,f)&&p.push(a[e]);d[e]=f;e++}return c&&(p=b?p.sort(function(a,c){return a[b]>c[b]}):p.sort()),p}function ea(a,b){for(var c,p,d=b[0].toUpperCase()+b.slice(1),e=0;e<Ba.length;){if(c=Ba[e],p=c?c+d:b,p in a)return p;e++}return g}function h(a){a=a.ownerDocument;return a.defaultView||a.parentWindow}function H(a,b){var c=this;this.manager=
a;this.callback=b;this.element=a.element;this.target=a.options.inputTarget;this.domHandler=function(b){N(a.options.enable,[a])&&c.handler(b)};this.init()}function fa(b){var c,p=b.options.inputClass;return c=p?p:Na?G:Oa?V:Ca?I:u,new c(b,a)}function a(a,b,c){var p=c.pointers.length,d=c.changedPointers.length,e=b&O&&0===p-d;p=b&(K|P)&&0===p-d;c.isFirst=!!e;c.isFinal=!!p;e&&(a.session={});c.eventType=b;b=a.session;e=c.pointers;p=e.length;b.firstInput||(b.firstInput=B(c));1<p&&!b.firstMultiple?b.firstMultiple=
B(c):1===p&&(b.firstMultiple=!1);d=b.firstInput;var h=(p=b.firstMultiple)?p.center:d.center,k=c.center=f(e);c.timeStamp=A();c.deltaTime=c.timeStamp-d.timeStamp;c.angle=r(h,k);c.distance=T(h,k);d=c.center;h=b.offsetDelta||{};k=b.prevDelta||{};var ca=b.prevInput||{};(c.eventType===O||ca.eventType===K)&&(k=b.prevDelta={x:ca.deltaX||0,y:ca.deltaY||0},h=b.offsetDelta={x:d.x,y:d.y});c.deltaX=k.x+(d.x-h.x);c.deltaY=k.y+(d.y-h.y);c.offsetDirection=L(c.deltaX,c.deltaY);p?(d=p.pointers,d=T(e[0],e[1],ta)/T(d[0],
d[1],ta)):d=1;c.scale=d;p?(p=p.pointers,e=r(e[1],e[0],ta)-r(p[1],p[0],ta)):e=0;c.rotation=e;h=b.lastInterval||c;e=c.timeStamp-h.timeStamp;c.eventType!=P&&(e>xa||h.velocity===g)?(d=h.deltaX-c.deltaX,h=h.deltaY-c.deltaY,k=d/e||0,ca=h/e||0,e=k,p=ca,k=ka(k)>ka(ca)?k:ca,d=L(d,h),b.lastInterval=c):(k=h.velocity,e=h.velocityX,p=h.velocityY,d=h.direction);c.velocity=k;c.velocityX=e;c.velocityY=p;c.direction=d;b=a.element;n(c.srcEvent.target,b)&&(b=c.srcEvent.target);c.target=b;a.emit("hammer.input",c);a.recognize(c);
a.session.prevInput=c}function B(a){for(var b=[],c=0;c<a.pointers.length;)b[c]={clientX:C(a.pointers[c].clientX),clientY:C(a.pointers[c].clientY)},c++;return{timeStamp:A(),pointers:b,center:f(b),deltaX:a.deltaX,deltaY:a.deltaY}}function f(a){var b=a.length;if(1===b)return{x:C(a[0].clientX),y:C(a[0].clientY)};for(var c=0,d=0,p=0;b>p;)c+=a[p].clientX,d+=a[p].clientY,p++;return{x:C(c/b),y:C(d/b)}}function L(a,b){return a===b?qa:ka(a)>=ka(b)?0<a?ha:ia:0<b?ja:la}function T(a,b,c){c||(c=Da);var d=b[c[0]]-
a[c[0]];a=b[c[1]]-a[c[1]];return Math.sqrt(d*d+a*a)}function r(a,b,c){c||(c=Da);return 180*Math.atan2(b[c[1]]-a[c[1]],b[c[0]]-a[c[0]])/Math.PI}function u(){this.evEl=Pa;this.evWin=Qa;this.allow=!0;this.pressed=!1;H.apply(this,arguments)}function G(){this.evEl=Ea;this.evWin=Fa;H.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function F(){this.evTarget=Ra;this.evWin=Sa;this.started=!1;H.apply(this,arguments)}function V(){this.evTarget=Ta;this.targetIds={};H.apply(this,arguments)}
function Ja(a,b){var c=aa(a.touches),d=this.targetIds;if(b&(O|ba)&&1===c.length)return d[c[0].identifier]=!0,[c,c];var p,e=aa(a.changedTouches),f=[],g=this.target;if(p=c.filter(function(a){return n(a.target,g)}),b===O)for(c=0;c<p.length;)d[p[c].identifier]=!0,c++;for(c=0;c<e.length;)d[e[c].identifier]&&f.push(e[c]),b&(K|P)&&delete d[e[c].identifier],c++;return f.length?[k(p.concat(f),"identifier",!0),f]:void 0}function I(){H.apply(this,arguments);var a=Z(this.handler,this);this.touch=new V(this.manager,
a);this.mouse=new u(this.manager,a)}function Q(a,b){this.manager=a;this.set(b)}function M(a){if(-1<a.indexOf(ma))return ma;var b=-1<a.indexOf(na),c=-1<a.indexOf(oa);return b&&c?na+" "+oa:b||c?b?na:oa:-1<a.indexOf(ya)?ya:Ga}function v(a){this.id=Ma++;this.manager=null;this.options=x(a||{},this.defaults);a=this.options.enable;this.options.enable=a===g?!0:a;this.state=ua;this.simultaneous={};this.requireFail=[]}function za(a){return a==la?"down":a==ja?"up":a==ha?"left":a==ia?"right":""}function w(a,
b){var c=b.manager;return c?c.get(a):a}function z(){v.apply(this,arguments)}function pa(){z.apply(this,arguments);this.pY=this.pX=null}function X(){z.apply(this,arguments)}function J(){v.apply(this,arguments);this._input=this._timer=null}function W(){z.apply(this,arguments)}function va(){z.apply(this,arguments)}function ra(){v.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function Y(a,b){b=b||{};var c=b.recognizers;return b.recognizers=c===g?Y.defaults.preset:
c,new wa(a,b)}function wa(a,b){b=b||{};this.options=x(b,Y.defaults);this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];this.element=a;this.input=fa(this);this.touchAction=new Q(this,this.options.touchAction);Aa(this,!0);c(b.recognizers,function(a){var b=this.add(new a[0](a[1]));a[2]&&b.recognizeWith(a[2]);a[3]&&b.requireFailure(a[3])},this)}function Aa(a,b){var d=a.element;c(a.options.cssProps,function(a,c){d.style[ea(d.style,c)]=b?a:""})}function Ka(a,
b){var c=t.createEvent("Event");c.initEvent(a,!0,!0);c.gesture=b;b.target.dispatchEvent(c)}var Ba=" webkit moz MS ms o".split(" "),La=t.createElement("div"),D="function",C=Math.round,ka=Math.abs,A=Date.now,Ma=1,sa=/mobile|tablet|ip(ad|hone|od)|android/i,Ca="ontouchstart"in e,Na=ea(e,"PointerEvent")!==g,Oa=Ca&&sa.test(navigator.userAgent),xa=25,O=1,ba=2,K=4,P=8,qa=1,ha=2,ia=4,ja=8,la=16,U=ha|ia,da=ja|la;sa=U|da;var Da=["x","y"],ta=["clientX","clientY"];H.prototype={handler:function(){},init:function(){this.evEl&&
l(this.element,this.evEl,this.domHandler);this.evTarget&&l(this.target,this.evTarget,this.domHandler);this.evWin&&l(h(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&R(this.element,this.evEl,this.domHandler);this.evTarget&&R(this.target,this.evTarget,this.domHandler);this.evWin&&R(h(this.element),this.evWin,this.domHandler)}};var Ua={mousedown:O,mousemove:ba,mouseup:K},Pa="mousedown",Qa="mousemove mouseup";d(u,H,{handler:function(a){var b=Ua[a.type];b&O&&0===a.button&&(this.pressed=
!0);b&ba&&1!==a.which&&(b=K);this.pressed&&this.allow&&(b&K&&(this.pressed=!1),this.callback(this.manager,b,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});var Va={pointerdown:O,pointermove:ba,pointerup:K,pointercancel:P,pointerout:P},Wa={2:"touch",3:"pen",4:"mouse",5:"kinect"},Ea="pointerdown",Fa="pointermove pointerup pointercancel";e.MSPointerEvent&&(Ea="MSPointerDown",Fa="MSPointerMove MSPointerUp MSPointerCancel");d(G,H,{handler:function(a){var b=this.store,c=!1,d=a.type.toLowerCase().replace("ms",
"");d=Va[d];var e=Wa[a.pointerType]||a.pointerType,p="touch"==e,f=S(b,a.pointerId,"pointerId");d&O&&(0===a.button||p)?0>f&&(b.push(a),f=b.length-1):d&(K|P)&&(c=!0);0>f||(b[f]=a,this.callback(this.manager,d,{pointers:b,changedPointers:[a],pointerType:e,srcEvent:a}),c&&b.splice(f,1))}});var Xa={touchstart:O,touchmove:ba,touchend:K,touchcancel:P},Ra="touchstart",Sa="touchstart touchmove touchend touchcancel";d(F,H,{handler:function(a){var b=Xa[a.type];if(b===O&&(this.started=!0),this.started){var c=
aa(a.touches);var d=aa(a.changedTouches);d=(b&(K|P)&&(c=k(c.concat(d),"identifier",!0)),[c,d]);b&(K|P)&&0===d[0].length-d[1].length&&(this.started=!1);this.callback(this.manager,b,{pointers:d[0],changedPointers:d[1],pointerType:"touch",srcEvent:a})}}});var Ya={touchstart:O,touchmove:ba,touchend:K,touchcancel:P},Ta="touchstart touchmove touchend touchcancel";d(V,H,{handler:function(a){var b=Ya[a.type],c=Ja.call(this,a,b);c&&this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",
srcEvent:a})}});d(I,H,{handler:function(a,b,c){var d="mouse"==c.pointerType;if("touch"==c.pointerType)this.mouse.allow=!1;else if(d&&!this.mouse.allow)return;b&(K|P)&&(this.mouse.allow=!0);this.callback(a,b,c)},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var Ha=ea(La.style,"touchAction"),Ia=Ha!==g,Ga="auto",ya="manipulation",ma="none",na="pan-x",oa="pan-y";Q.prototype={set:function(a){"compute"==a&&(a=this.compute());Ia&&(this.manager.element.style[Ha]=a);this.actions=a.toLowerCase().trim()},
update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];return c(this.manager.recognizers,function(b){N(b.options.enable,[b])&&(a=a.concat(b.getTouchAction()))}),M(a.join(" "))},preventDefaults:function(a){if(!Ia){var b=a.srcEvent;a=a.offsetDirection;if(this.manager.session.prevented)return b.preventDefault(),void 0;var c=this.actions,d=-1<c.indexOf(ma),e=-1<c.indexOf(oa);c=-1<c.indexOf(na);return d||e&&a&U||c&&a&da?this.preventSrc(b):void 0}},preventSrc:function(a){this.manager.session.prevented=
!0;a.preventDefault()}};var ua=1;v.prototype={defaults:{},set:function(a){return E(this.options,a),this.manager&&this.manager.touchAction.update(),this},recognizeWith:function(a){if(m(a,"recognizeWith",this))return this;var b=this.simultaneous;return a=w(a,this),b[a.id]||(b[a.id]=a,a.recognizeWith(this)),this},dropRecognizeWith:function(a){return m(a,"dropRecognizeWith",this)?this:(a=w(a,this),delete this.simultaneous[a.id],this)},requireFailure:function(a){if(m(a,"requireFailure",this))return this;
var b=this.requireFail;return a=w(a,this),-1===S(b,a)&&(b.push(a),a.requireFailure(this)),this},dropRequireFailure:function(a){if(m(a,"dropRequireFailure",this))return this;a=w(a,this);a=S(this.requireFail,a);return-1<a&&this.requireFail.splice(a,1),this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function b(b){c.manager.emit(c.options.event+(b?d&16?"cancel":d&8?"end":d&4?"move":d&2?"start":"":""),
a)}var c=this,d=this.state;8>d&&b(!0);b();8<=d&&b(!0)},tryEmit:function(a){return this.canEmit()?this.emit(a):(this.state=32,void 0)},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&(32|ua)))return!1;a++}return!0},recognize:function(a){a=E({},a);return N(this.options.enable,[this,a])?(this.state&56&&(this.state=ua),this.state=this.process(a),this.state&30&&this.tryEmit(a),void 0):(this.reset(),this.state=32,void 0)},process:function(){},getTouchAction:function(){},
reset:function(){}};d(z,v,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},process:function(a){var b=this.state,c=a.eventType,d=b&6;a=this.attrTest(a);return d&&(c&P||!a)?b|16:d||a?c&K?b|8:b&2?b|4:2:32}});d(pa,z,{defaults:{event:"pan",threshold:10,pointers:1,direction:sa},getTouchAction:function(){var a=this.options.direction,b=[];return a&U&&b.push(oa),a&da&&b.push(na),b},directionTest:function(a){var b=this.options,c=!0,d=a.distance,e=
a.direction,f=a.deltaX,g=a.deltaY;return e&b.direction||(b.direction&U?(e=0===f?qa:0>f?ha:ia,c=f!=this.pX,d=Math.abs(a.deltaX)):(e=0===g?qa:0>g?ja:la,c=g!=this.pY,d=Math.abs(a.deltaY))),a.direction=e,c&&d>b.threshold&&e&b.direction},attrTest:function(a){return z.prototype.attrTest.call(this,a)&&(this.state&2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var b=za(a.direction);b&&this.manager.emit(this.options.event+b,a);this._super.emit.call(this,a)}});
d(X,z,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return[ma]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.scale-1)>this.options.threshold||this.state&2)},emit:function(a){(this._super.emit.call(this,a),1!==a.scale)&&this.manager.emit(this.options.event+(1>a.scale?"in":"out"),a)}});d(J,v,{defaults:{event:"press",pointers:1,time:500,threshold:5},getTouchAction:function(){return[Ga]},process:function(a){var b=this.options,c=a.pointers.length===
b.pointers,d=a.distance<b.threshold,e=a.deltaTime>b.time;if(this._input=a,!d||!c||a.eventType&(K|P)&&!e)this.reset();else if(a.eventType&O)this.reset(),this._timer=y(function(){this.state=8;this.tryEmit()},b.time,this);else if(a.eventType&K)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){8===this.state&&(a&&a.eventType&K?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=A(),this.manager.emit(this.options.event,this._input)))}});d(W,z,{defaults:{event:"rotate",
threshold:0,pointers:2},getTouchAction:function(){return[ma]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>this.options.threshold||this.state&2)}});d(va,z,{defaults:{event:"swipe",threshold:10,velocity:.65,direction:U|da,pointers:1},getTouchAction:function(){return pa.prototype.getTouchAction.call(this)},attrTest:function(a){var b,c=this.options.direction;return c&(U|da)?b=a.velocity:c&U?b=a.velocityX:c&da&&(b=a.velocityY),this._super.attrTest.call(this,a)&&
c&a.direction&&a.distance>this.options.threshold&&ka(b)>this.options.velocity&&a.eventType&K},emit:function(a){var b=za(a.direction);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,a)}});d(ra,v,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:2,posThreshold:10},getTouchAction:function(){return[ya]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime<b.time;if(this.reset(),a.eventType&
O&&0===this.count)return this.failTimeout();if(d&&e&&c){if(a.eventType!=K)return this.failTimeout();c=this.pTime?a.timeStamp-this.pTime<b.interval:!0;d=!this.pCenter||T(this.pCenter,a.center)<b.posThreshold;this.pTime=a.timeStamp;this.pCenter=a.center;d&&c?this.count+=1:this.count=1;this._input=a;if(0===this.count%b.taps)return this.hasRequireFailures()?(this._timer=y(function(){this.state=8;this.tryEmit()},b.interval,this),2):8}return 32},failTimeout:function(){return this._timer=y(function(){this.state=
32},this.options.interval,this),32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});Y.VERSION="2.0.4";Y.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[W,{enable:!1}],[X,{enable:!1},["rotate"]],[va,{direction:U}],[pa,{direction:U},["swipe"]],[ra],[ra,{event:"doubletap",taps:2},["tap"]],[J]],cssProps:{userSelect:"default",touchSelect:"none",
touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};wa.prototype={set:function(a){return E(this.options,a),a.touchAction&&this.touchAction.update(),a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init()),this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=this.session;if(!b.stopped){this.touchAction.preventDefaults(a);var c=this.recognizers,d=b.curRecognizer;(!d||d&&d.state&8)&&(d=b.curRecognizer=
null);for(var e=0;e<c.length;){var f=c[e];2===b.stopped||d&&f!=d&&!f.canRecognizeWith(d)?f.reset():f.recognize(a);!d&&f.state&14&&(d=b.curRecognizer=f);e++}}},get:function(a){if(a instanceof v)return a;for(var b=this.recognizers,c=0;c<b.length;c++)if(b[c].options.event==a)return b[c];return null},add:function(a){if(m(a,"add",this))return this;var b=this.get(a.options.event);return b&&this.remove(b),this.recognizers.push(a),a.manager=this,this.touchAction.update(),a},remove:function(a){if(m(a,"remove",
this))return this;var b=this.recognizers;return a=this.get(a),b.splice(S(b,a),1),this.touchAction.update(),this},on:function(a,b){var d=this.handlers;return c(q(a),function(a){d[a]=d[a]||[];d[a].push(b)}),this},off:function(a,b){var d=this.handlers;return c(q(a),function(a){b?d[a].splice(S(d[a],b),1):delete d[a]}),this},emit:function(a,b){this.options.domEvents&&Ka(a,b);var c=this.handlers[a]&&this.handlers[a].slice();if(c&&c.length){b.type=a;b.preventDefault=function(){b.srcEvent.preventDefault()};
for(var d=0;d<c.length;)c[d](b),d++}},destroy:function(){this.element&&Aa(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};E(Y,{INPUT_START:O,INPUT_MOVE:ba,INPUT_END:K,INPUT_CANCEL:P,STATE_POSSIBLE:ua,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:qa,DIRECTION_LEFT:ha,DIRECTION_RIGHT:ia,DIRECTION_UP:ja,DIRECTION_DOWN:la,DIRECTION_HORIZONTAL:U,DIRECTION_VERTICAL:da,DIRECTION_ALL:sa,Manager:wa,Input:H,
TouchAction:Q,TouchInput:V,MouseInput:u,PointerEventInput:G,TouchMouseInput:I,SingleTouchInput:F,Recognizer:v,AttrRecognizer:z,Tap:ra,Pan:pa,Swipe:va,Pinch:X,Rotate:W,Press:J,on:l,off:R,each:c,merge:x,extend:E,inherit:d,bindFn:Z,prefixed:ea});typeof define==D&&define.amd?define(function(){return Y}):"undefined"!=typeof module&&module.exports?module.exports=Y:e[b]=Y}(window,document,"Hammer");
(function(e){"function"===typeof define&&define.amd?define(["jquery","hammerjs"],e):"object"===typeof exports?e(require("jquery"),require("hammerjs")):e(jQuery,Hammer)})(function(e,t){e.fn.hammer=function(b){return this.each(function(){var g=e(this);g.data("hammer")||g.data("hammer",new t(g[0],b))})};t.Manager.prototype.emit=function(b){return function(g,t){b.call(this,g,t);e(this.element).trigger({type:g,gesture:t})}}(t.Manager.prototype.emit)});
var methods={init:function(){return this.each(function(){var e=$(this);$(window).width();e.width("100%");var t=$(this).children("li").length;e.children("li").each(function(){$(this).width(100/t+"%")});var b=e.find("li.tab a"),g=e.width(),y=e.find("li").first().outerWidth(),m=0;var c=$(b.filter('[href="'+location.hash+'"]'));0===c.length&&(c=$(this).find("li.tab a.active").first());0===c.length&&(c=$(this).find("li.tab a").first());c.addClass("active");m=b.index(c);0>m&&(m=0);var E=$(c[0].hash);e.append('<div class="indicator"></div>');
var x=e.find(".indicator");e.is(":visible")&&(x.css({right:g-(m+1)*y}),x.css({left:m*y}));$(window).resize(function(){g=e.width();y=e.find("li").first().outerWidth();0>m&&(m=0);0!==y&&0!==g&&(x.css({right:g-(m+1)*y}),x.css({left:m*y}))});b.not(c).each(function(){$(this.hash).hide()});e.on("click","a",function(d){g=e.width();y=e.find("li").first().outerWidth();c.removeClass("active");E.hide();c=$(this);E=$(this.hash);b=e.find("li.tab a");c.addClass("active");var t=m;m=b.index($(this));0>m&&(m=0);E.show();
0<=m-t?(x.velocity({right:g-(m+1)*y},{duration:300,queue:!1,easing:"easeOutQuad"}),x.velocity({left:m*y},{duration:300,queue:!1,easing:"easeOutQuad",delay:90})):(x.velocity({left:m*y},{duration:300,queue:!1,easing:"easeOutQuad"}),x.velocity({right:g-(m+1)*y},{duration:300,queue:!1,easing:"easeOutQuad",delay:90}));d.preventDefault()})})},select_tab:function(e){this.find('a[href="#'+e+'"]').trigger("click")}};
$.fn.tabs=function(e){if(methods[e])return methods[e].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof e&&e)$.error("Method "+e+" does not exist on jQuery.tooltip");else return methods.init.apply(this,arguments)};$(document).ready(function(){$("ul.tabs").tabs()});
